# Generated by Django 3.2.8 on 2021-10-29 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="parent",
            field=models.ManyToManyField(
                blank=True,
                related_name="_registration_person_parent_+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="siblings",
            field=models.ManyToManyField(
                blank=True,
                related_name="_registration_person_siblings_+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
