# Generated by Django 3.2.8 on 2021-10-29 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_auto_20211029_1009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="parent",
            field=models.ManyToManyField(
                blank=True, related_name="person_parent", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
