# Generated by Django 3.2.8 on 2021-10-30 05:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_alter_person_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
